"""Evidence transparency primitives."""

from cc.evidence.anchoring import (
    Ed25519Witness,
    RootAnchor,
    RootCheckpoint,
    WitnessSignature,
    anchor_root,
    verify_anchor,
)
from cc.evidence.assurance_schema import (
    ASSURANCE_SCHEMA_VERSION,
    Assumption,
    AssuranceCase,
    ClaimCategory,
    Context,
    Defeater,
    Evidence,
    EvidenceRole,
    ReviewStatus,
    Strategy,
    SubClaim,
    TopClaim,
    assurance_case_from_run,
    export_assurance_case_jsonld,
    export_assurance_case_markdown,
    write_assurance_case_exports,
)
from cc.evidence.claim_governance import (
    ClaimGovernanceAudit,
    GovernanceVerdict,
    verify_claim_governance,
)
from cc.evidence.decay import (
    CLAIM_DECAY_SCHEMA_VERSION,
    ClaimDecayPolicy,
    ClaimDecayRecord,
    DecayState,
    DecayStatus,
    evaluate_claim_decay,
)
from cc.evidence.extremal_scenario import (
    EXTREMAL_SCENARIO_SCHEMA_VERSION,
    ExtremalScenario,
    GuardrailOutcome,
    ScenarioKind,
)
from cc.evidence.merkle_log import (
    ConsistencyProof,
    InclusionProof,
    MerkleLog,
    MerkleLogError,
    leaf_hash,
    root_from_records,
    verify_consistency,
    verify_inclusion,
)

CLAIM_DECAY_SCHEMA = CLAIM_DECAY_SCHEMA_VERSION
EXTREMAL_SCENARIO_SCHEMA = EXTREMAL_SCENARIO_SCHEMA_VERSION

__all__ = [
    "ASSURANCE_SCHEMA_VERSION",
    "CLAIM_DECAY_SCHEMA",
    "CLAIM_DECAY_SCHEMA_VERSION",
    "EXTREMAL_SCENARIO_SCHEMA",
    "EXTREMAL_SCENARIO_SCHEMA_VERSION",
    "Assumption",
    "AssuranceCase",
    "ClaimCategory",
    "ClaimDecayPolicy",
    "ClaimDecayRecord",
    "ClaimGovernanceAudit",
    "ConsistencyProof",
    "Context",
    "DecayState",
    "DecayStatus",
    "Defeater",
    "Ed25519Witness",
    "Evidence",
    "EvidenceRole",
    "ExtremalScenario",
    "GovernanceVerdict",
    "GuardrailOutcome",
    "InclusionProof",
    "MerkleLog",
    "MerkleLogError",
    "ReviewStatus",
    "RootAnchor",
    "RootCheckpoint",
    "ScenarioKind",
    "Strategy",
    "SubClaim",
    "TopClaim",
    "WitnessSignature",
    "anchor_root",
    "assurance_case_from_run",
    "evaluate_claim_decay",
    "export_assurance_case_jsonld",
    "export_assurance_case_markdown",
    "leaf_hash",
    "root_from_records",
    "verify_anchor",
    "verify_claim_governance",
    "verify_consistency",
    "verify_inclusion",
    "write_assurance_case_exports",
]
