"""Numerical kernels for dependency-sensitive probability bounds."""

from cc.kernel.frechet_classes import (
    FrechetBoundResult,
    FrechetClassInfeasibleError,
    PairwiseDependence,
    PairwiseJointConstraint,
    atom_matrix,
    classical_frechet_bounds,
    dependence_to_joint_probability,
    distribution_moments,
    event_probability,
    frechet_bounds,
    improved_frechet_bounds,
    joint_probability_to_dependence,
    pairwise_correlation_bounds,
    random_feasible_distribution,
    sample_binary_vectors,
)
from cc.kernel.cliff import (
    CliffCertificate,
    CopulaCandidateFit,
    CopulaFitResult,
    TailDependenceCI,
    TailDependenceEstimate,
    bootstrap_tail_dependence_ci,
    cliff_certificate,
    estimate_tail_dependence,
    fit_copula_family,
    sample_copula,
    theoretical_tail_dependence,
)

__all__ = [
    "CliffCertificate",
    "CopulaCandidateFit",
    "CopulaFitResult",
    "FrechetBoundResult",
    "FrechetClassInfeasibleError",
    "PairwiseDependence",
    "PairwiseJointConstraint",
    "TailDependenceCI",
    "TailDependenceEstimate",
    "atom_matrix",
    "bootstrap_tail_dependence_ci",
    "classical_frechet_bounds",
    "cliff_certificate",
    "dependence_to_joint_probability",
    "distribution_moments",
    "estimate_tail_dependence",
    "event_probability",
    "fit_copula_family",
    "frechet_bounds",
    "improved_frechet_bounds",
    "joint_probability_to_dependence",
    "pairwise_correlation_bounds",
    "random_feasible_distribution",
    "sample_binary_vectors",
    "sample_copula",
    "theoretical_tail_dependence",
]
