"""Bounded red-team discovery utilities for dependence-aware guardrail audits."""

from .dependence_search import (
    BoundedParaphraseConfig,
    CandidateInput,
    ContentSafetyGate,
    ContentSafetyGateConfig,
    DependenceMetrics,
    DependenceSearchConfig,
    DependenceSearchContext,
    DependenceSearchResult,
    DiscoveredCliffReport,
    ObjectiveConfig,
    PerturbationSpaceConfig,
    PhraseRewrite,
    PublicPromptInjectionConfig,
    PublicPromptInjectionPattern,
    SafetyDecision,
    SimulatedAnnealingSearch,
    SimulatedAnnealingSearchConfig,
    SynonymSubstitutionConfig,
    compute_dependence_metrics,
    dependence_search_config_schema,
    evaluate_baseline_metrics,
    load_prompt_corpus,
    run_dependence_search,
    write_discovered_cliff_report,
)

__all__ = [
    "BoundedParaphraseConfig",
    "CandidateInput",
    "ContentSafetyGate",
    "ContentSafetyGateConfig",
    "DependenceMetrics",
    "DependenceSearchConfig",
    "DependenceSearchContext",
    "DependenceSearchResult",
    "DiscoveredCliffReport",
    "ObjectiveConfig",
    "PerturbationSpaceConfig",
    "PhraseRewrite",
    "PublicPromptInjectionConfig",
    "PublicPromptInjectionPattern",
    "SafetyDecision",
    "SimulatedAnnealingSearch",
    "SimulatedAnnealingSearchConfig",
    "SynonymSubstitutionConfig",
    "compute_dependence_metrics",
    "dependence_search_config_schema",
    "evaluate_baseline_metrics",
    "load_prompt_corpus",
    "run_dependence_search",
    "write_discovered_cliff_report",
]
